-- Historical migration marker.
--
-- This version is already recorded in the production migration history. Its
-- former duplicate function body now lives in 20260624203000, including the
-- PostgREST schema-cache notification.
