-- Historical migration marker.
--
-- This version is already recorded in the production migration history. The
-- canonical post and task delete policies are maintained by
-- 20260626213000_storage_and_attachment_management.sql.
